address: "0.0.0.0:8888"
logfile: "/tmp/nautilus.log"

postgres:
  master: "postgres://yangjinlong:postgres@localhost:5432/nautilus?sslmode=disable"
  slave1: "postgres://yangjinlong:postgres@localhost:5432/nautilus?sslmode=disable"
  slave2: "postgres://yangjinlong:postgres@localhost:5432/nautilus?sslmode=disable"

rabbitmq:
  address: "amqp://rabbit:yangjinlong@10.12.24.19:5672/core"
  exchange: "nautilus"
  queue: "all-build-image"
  routingKey: "build-image"

k8s:
  kubeconfig: "/Users/yangjinlong/.kube/config"
  deployment: "https://%s:6443/apis/apps/v1/namespaces/%s/deployments"
  service: "https://%s:6443/api/v1/namespaces/%s/services"
  configmap: "https://%s:6443/api/v1/namespaces/%s/configmaps"
  token: "eyJhbGciOiJSUzI1NiIsImtpZCI6Imt4U0F4Qlh2RU9ncU51MktsWk54WFZGZ3FMS3N5QkhaNVdNQXpHVHU5Wk0ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRlZmF1bHQtdG9rZW4tam01MnEiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGVmYXVsdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImM2YTU5ZWZlLWVjYzYtNDc2ZC05YzhmLWU1ODA0YTNlNDVmOCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmRlZmF1bHQifQ.drkp9D_Fqu2hJyt_G3TY4xtXxPYa1RldlVl67gDxnIjCU3MVrR5cnEcLgVzohoUGt6wxburn6vptAX2-4KXrZAEknbTw55KgunpLlzhgERsTi7zaaxF5UPA5tPt26PqyHIQ2bkx7jbE-DmOJ7W-kkRx6SHhSpYhkyQ7IoqwIGpbFJR4jBcazmiRJ7k8wR5--HB1gER4np3DK0i-WSArK-5ig2x5DII4f8n1FEb-EhufxoMFBnzbOmzXA8lA85DaERl1pvQEvej3cgAhKnOtTKNwFAhfXJHtxlQ5LjXezV5kIxcsizH4ZWzV1s9hPHi1SUwXagbQJLRTs8q_2-2JhFA"

cluster:
  hp: '10.12.28.4'
  xq: '10.12.28.4'

image:
  logfile: "/tmp/nautilus-image.log"
  registry: "10.12.28.4:80/release"
  dir: "/tmp/release"

informer:
  logfile: "/tmp/nautilus-informer.log"
