address: "0.0.0.0:8888"
logfile: "/tmp/nautilus.log"

postgres:
  master: "postgres://yangjinlong:postgres@localhost:5432/nautilus?sslmode=disable"
  slave1: "postgres://yangjinlong:postgres@localhost:5432/nautilus?sslmode=disable"
  slave2: "postgres://yangjinlong:postgres@localhost:5432/nautilus?sslmode=disable"

k8s:
  hpconfig: "/Users/yangjinlong/.kube/config"
  xqconfig: "/Users/yangjinlong/.kube/config"
  imageKey: "harborkey"

rabbitmq:
  address: "amqp://rabbit:yangjinlong@10.12.24.19:5672/core"
  exchange: "nautilus"
  queue: "all-build-image"
  routingKey: "build-image"

image:
  release: "/tmp/release"
  registry: "10.12.28.4:80/release"
