address: "0.0.0.0:8888"
logfile: "/tmp/nautilus.log"

postgres:
  master: "postgres://yangjinlong:postgres@localhost:5432/nautilus?sslmode=disable"
  slave1: "postgres://yangjinlong:postgres@localhost:5432/nautilus?sslmode=disable"
  slave2: "postgres://yangjinlong:postgres@localhost:5432/nautilus?sslmode=disable"

rabbitmq:
  address: "amqp://rabbit:yangjinlong@10.12.24.19:5672/core"
  exchange: "nautilus"
  queue: "all-build-image"
  routingKey: "build-image"

k8s:
  kubeconfig: "/Users/yangjinlong/.kube/config"
  deployment: "https://%s:6443/apis/apps/v1/namespaces/%s/deployments"
  service: "https://%s:6443/api/v1/namespaces/%s/services"
  configmap: "https://%s:6443/api/v1/namespaces/%s/configmaps"

cluster:
  hp: '10.12.28.4'
  xq: '10.12.28.4'

image:
  logfile: "/tmp/nautilus-image.log"
  registry: "10.12.28.4:80/release"
  dir: "/tmp/release"

informer:
  logfile: "/tmp/nautilus-informer.log"
