logfile: "/tmp/ferry.log"

bootstrap:
  address: "0.0.0.0:8888"
  readTimeout: 0       # 0 means no limit
  writeTimeout: 0      # 0 means no limit
  maxHeaderBytes: 8192 # 8K
  exitWaitSecond: 1    # 退出等待时间

postgres:
  master: "postgres://jinlong:postgres@localhost:5432/ferry?sslmode=disable"
  slave1: "postgres://jinlong:postgres@localhost:5432/ferry?sslmode=disable"
  slave2: "postgres://jinlong:postgres@localhost:5432/ferry?sslmode=disable"

rabbitmq:
  address: "amqp://rabbit:yangjinlong@10.12.24.19:5672/core"
  exchange: "ferry"
  queue: "all-build-image"
  routingKey: "build-image"

build:
  dir: "/tmp/release"
  logfile: "/tmp/image.log"

watch:
  logfile: "/tmp/deploy.log"

registry:
  release: "10.12.28.4:80/release"

k8s:
  kubeconfig: "/Users/yangyutong/.kube/config"
  deployment: "http://10.12.28.4:8080/apis/apps/v1/namespaces/%s/deployments"
  service: "http://10.12.28.4:8080/api/v1/namespaces/%s/services"
