address: "0.0.0.0:8888"

log:
  server: "/tmp/nautilus.log"
  informer: "/tmp/informer.log"

postgres:
  master: "postgres://yangjinlong:postgres@10.12.24.255:5432/nautilus?sslmode=disable"
  slave1: "postgres://yangjinlong:postgres@10.12.24.255:5432/nautilus?sslmode=disable"
  slave2: "postgres://yangjinlong:postgres@10.12.24.255:5432/nautilus?sslmode=disable"

k8s:
  hp: "/root/.kube/config"
  xq: "/root/.kube/config"
  imageKey: "harborkey"
